language: python
dist: xenial
sudo: false
script: tox
cache: pip
python:
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
install: pip install tox-travis tox flake8 coverage codecov
after_success: codecov
services: redis-server
jobs:
  include:
    - name: 'Test demo app'
      python: '3.7'
      install: pip install codecov -r requirements.txt
      env:
        CELERY_BROKER_URL=redis://0.0.0.0:6379
        DJANGO_SETTINGS_MODULE=config.settings.test_demo_app
      script:
        - pytest --cov=./django_structlog_demo_project --cov-append django_structlog_demo_project
    - name: 'Test build doc'
      python: '3.7'
      install: pip install -r requirements/doc.txt
      script:
        - cd docs
        - make html
        - make doctest
      services: []
      after_success: skip
    - stage: linter
      name: 'black'
      python: '3.7'
      install: pip install black
      script: black --check --verbose .
      services: []
      after_success: skip
    - stage: linter
      name: 'flake8'
      python: '3.7'
      install: pip install flake8
      script: flake8
      services: []
      after_success: skip
    - stage: deploy
      name: 'PyPI deployment'
      python: '3.7'
      script: skip
      services: []
      install: skip
      deploy:
        provider: pypi
        user: jrobichaud
        password:
          secure: mjxvOZoN6CY0MT/t1xd0MvqCihpdgbj4qCvO9ruduI8Nnwr8uxIKBZwK8WUCA7OZXxMg8OdAkitmMgbDQasqcg8/HMuerEjMDdooMjuX4LMJU0rSGwWU31JIaby8ypJdFd2R3Ir6T4wV2V1ajW+HjwpqLKMsQFhZOgl/x0S5V2CayS+zOi4U/2SNmosRWqQ7Kki7rM3bw7twY+YEz76NJVTdlT/BGjjFSDCP4gWoGgQboPgskolom+56ScW/kePbONoqlO8S3Kml3svTX1Yz8P1DYcKylUQJ8Vb4wWzm6ALbbN71a7jYI81bHN7v3JvW7seEkCEOFdyaH7hLV2YMX3SnBVeIeOtkJuFemUTBuPgbN6d4vEqFrsyiZpbBNNzD5MoGfZSHpFlqUo4CsTg7Urn6D2xqVnxg9JWFo6ZntoCIQv9c7j8tKB5nA2EeZahtUZSS0GN6m2Cu9ty2qXHp37mqNd4MaQHrrGA2BJ/MTqrPbZIE/9YejD/E65DANRZ2KMNZjebm6kMEns1Pe3JG3e+YAKRGbTs+dU0DZkwOgq8mHc41j18HYIEsK0XA5tI6J7fAKgSUoC+bgtsPIPZeLaFDtpQJugLr0Gp946sQwa2K1JMl/euWgXVZ9H0qz+hGzT7bUdhjPVPa2GrldTsifPdqK9tA11GQ18hfKkR5c8U=
        on:
          tags: true
        distributions: "sdist bdist_wheel"
