language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
env:
    - DJANGO_SETTINGS_MODULE=django_structlog_demo_project.settings
install:
  - pip install tox-travis tox flake8 coverage codecov
dist: xenial
sudo: false
script: tox
before_script:
  - flake8 django_structlog --ignore=E501,E128,E402
after_script:
  - codecov
