version: '3'

services:
  docs:
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    image: django_structlog_demo_project_docs
    volumes:
      - .:/app:cached
    working_dir: /app
    ports:
      - "5000:5000"
    command: /start
  docs-test:
    image: django_structlog_demo_project_docs
    volumes:
      - .:/app:cached
    working_dir: /app/docs
    command: make doctest
