version: '3'

services:
  docs:
    build:
      context: .
      dockerfile: ./compose/local/doc/Dockerfile
    image: django_structlog_demo_project_docs
    volumes:
      - .:/app:cached
    working_dir: /app
    ports:
      - "5000:5000"
    command: [
      "sphinx-autobuild", "docs", "docs/_build/html",
      "-p", "5000",
      "-H", "0.0.0.0",
      "--watch", "django_structlog",
      "--ignore", "*___jb_*",
      "--ignore", "docs/_build/*",
    ]
  docs-test:
    image: django_structlog_demo_project_docs
    volumes:
      - .:/app:cached
    working_dir: /app/docs
    command: make doctest
